<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="6" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-16T11:25:37 IST" name="Suite" finished-at="2024-06-16T11:25:54 IST" duration-ms="17162">
    <groups>
    </groups>
    <test started-at="2024-06-16T11:25:37 IST" name="Error Validations" finished-at="2024-06-16T11:25:52 IST" duration-ms="14630">
      <class name="Maven_TestNG.Tests.ErrorValidation">
        <test-method is-config="true" signature="launchapp()[pri:0, instance:Maven_TestNG.Tests.ErrorValidation@33fe57a9]" started-at="2024-06-16T11:25:37 IST" name="launchapp" finished-at="2024-06-16T11:25:40 IST" duration-ms="3242" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method retried="true" signature="errorMessage()[pri:48, instance:Maven_TestNG.Tests.ErrorValidation@33fe57a9]" started-at="2024-06-16T11:25:40 IST" name="errorMessage" finished-at="2024-06-16T11:25:41 IST" duration-ms="532" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect  or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect  or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Maven_TestNG.Tests.ErrorValidation.errorMessage(ErrorValidation.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorMessage -->
        <test-method is-config="true" signature="DriverClose()[pri:0, instance:Maven_TestNG.Tests.ErrorValidation@33fe57a9]" started-at="2024-06-16T11:25:41 IST" name="DriverClose" finished-at="2024-06-16T11:25:41 IST" duration-ms="185" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DriverClose -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:Maven_TestNG.Tests.ErrorValidation@33fe57a9]" started-at="2024-06-16T11:25:41 IST" name="launchapp" finished-at="2024-06-16T11:25:43 IST" duration-ms="1547" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="errorMessage()[pri:48, instance:Maven_TestNG.Tests.ErrorValidation@33fe57a9]" started-at="2024-06-16T11:25:43 IST" name="errorMessage" finished-at="2024-06-16T11:25:44 IST" duration-ms="1021" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect  or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect  or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Maven_TestNG.Tests.ErrorValidation.errorMessage(ErrorValidation.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorMessage -->
        <test-method is-config="true" signature="DriverClose()[pri:0, instance:Maven_TestNG.Tests.ErrorValidation@33fe57a9]" started-at="2024-06-16T11:25:44 IST" name="DriverClose" finished-at="2024-06-16T11:25:46 IST" duration-ms="1737" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DriverClose -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:Maven_TestNG.Tests.ErrorValidation@33fe57a9]" started-at="2024-06-16T11:25:46 IST" name="launchapp" finished-at="2024-06-16T11:25:48 IST" duration-ms="2553" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="errMsg2()[pri:49, instance:Maven_TestNG.Tests.ErrorValidation@33fe57a9]" started-at="2024-06-16T11:25:48 IST" name="errMsg2" finished-at="2024-06-16T11:25:51 IST" duration-ms="3016" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Maven_TestNG.Tests.ErrorValidation.errMsg2(ErrorValidation.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errMsg2 -->
        <test-method is-config="true" signature="DriverClose()[pri:0, instance:Maven_TestNG.Tests.ErrorValidation@33fe57a9]" started-at="2024-06-16T11:25:51 IST" name="DriverClose" finished-at="2024-06-16T11:25:52 IST" duration-ms="254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DriverClose -->
      </class> <!-- Maven_TestNG.Tests.ErrorValidation -->
    </test> <!-- Error Validations -->
    <test started-at="2024-06-16T11:25:37 IST" name="Stand Alone Test" finished-at="2024-06-16T11:25:54 IST" duration-ms="17162">
      <class name="Maven_TestNG.Tests.standAloneTest">
        <test-method is-config="true" signature="launchapp()[pri:0, instance:Maven_TestNG.Tests.standAloneTest@6eb2384f]" started-at="2024-06-16T11:25:37 IST" name="launchapp" finished-at="2024-06-16T11:25:40 IST" duration-ms="2926" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Maven_TestNG.Tests.standAloneTest@6eb2384f]" started-at="2024-06-16T11:25:40 IST" name="submitOrder" data-provider="getData" finished-at="2024-06-16T11:25:43 IST" duration-ms="2930" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Acc1234$$, email=mail7@mail7.io}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="DriverClose()[pri:0, instance:Maven_TestNG.Tests.standAloneTest@6eb2384f]" started-at="2024-06-16T11:25:43 IST" name="DriverClose" finished-at="2024-06-16T11:25:44 IST" duration-ms="416" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DriverClose -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:Maven_TestNG.Tests.standAloneTest@6eb2384f]" started-at="2024-06-16T11:25:44 IST" name="launchapp" finished-at="2024-06-16T11:25:48 IST" duration-ms="4400" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Maven_TestNG.Tests.standAloneTest@6eb2384f]" started-at="2024-06-16T11:25:48 IST" name="submitOrder" data-provider="getData" finished-at="2024-06-16T11:25:51 IST" duration-ms="3040" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=pwd1234$$, email=mail6@mail7.io}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="DriverClose()[pri:0, instance:Maven_TestNG.Tests.standAloneTest@6eb2384f]" started-at="2024-06-16T11:25:51 IST" name="DriverClose" finished-at="2024-06-16T11:25:54 IST" duration-ms="3085" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DriverClose -->
      </class> <!-- Maven_TestNG.Tests.standAloneTest -->
    </test> <!-- Stand Alone Test -->
  </suite> <!-- Suite -->
</testng-results>
